### ISSUE TITLE
Nest: HKSV doesn't record audio

### ISSUE THREAD

**Issue by n0rt0nthec4t** [n0rt0nthec4t/HAP-NodeJS-Accessories#10]
Know issue with current code based. Todo

**Comment by n0rt0nthec4t** [comment]
Test (alpha/beta) version uploaded.  [https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/blob/master/Nest/Nest_accfactory-testing.js](url)

**Comment by n0rt0nthec4t** [comment]
@krehman something to test

**Comment by n0rt0nthec4t** [comment]
@krehman interested to test a version which does audio recording?

**Comment by n0rt0nthec4t** [comment]
Committed change for testing

https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/commit/fc86ffa06644725591ed27b5d2bd8ffdb14ca091

And updated image file names

https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/commit/76afd8378277816652ef3c441dc3ffbd32482c8d

**Comment by krehman** [comment]
@n0rt0nthec4t apologies for the delay, got caught up with work. I have loaded the latest version and testing it now. Audio recordings are working. Awesome thanks!

**Comment by n0rt0nthec4t** [comment]
No worries. Keep an eye on audio sync. Took me a while to sort that out, but seems ok with my current test
