### ISSUE TITLE
Dockerize the HAP-NodeJS solution

### ISSUE THREAD

**Issue by krehman** [n0rt0nthec4t/HAP-NodeJS-Accessories#12]
Request to Dockerize the HAP-NodeJS with the Nest accessories.

**Comment by krehman** [comment]
@n0rt0nthec4t I'm only putting this in as an enhancement request for the future. I believe it may drive other testers to test this if it's in a Docker container.

**Comment by n0rt0nthec4t** [comment]
Unlikely I'll ever get to it, but never know

**Comment by krehman** [comment]
Yeah, no worries. I am trying to learn how to dockerize it as well. Just wanted to put out there if you ever get to it. You can tag it as "enhancement". Thanks.

**Comment by krehman** [comment]
I have created a docker image using the following `Dockerfile` and `.dockerignore` inside the [HAP-NodeJS-Accessories/Nest](https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/tree/master/Nest) folder.

Note - inside the [HAP-NodeJS-Accessories/Nest](https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/tree/master/Nest), create a `Nest_config.json` with the necessary details as it is used by `Dockerfile` to copy it to `hap-nodejs` folder.

I used [docker-homebridge](https://github.com/oznu/docker-homebridge/) project as my starting point.

**Dockerfile**
```
ARG S6_ARCH
FROM oznu/s6-node:16.15.0-r2-ubuntu-${S6_ARCH:-amd64}

WORKDIR /nest_accfactory

COPY package*.json ./

RUN npm install

COPY . .

CMD ["node", "Nest_accfactory.js"]
```
**.dockerignore**
```
.dockerignore
Dockerfile
```
To run the docker image, I used the following command, `docker run -d --net=host nest_accfactory`

TODO: clean-up docker image and provide flexibility to pass `Nest_config.json` as parameters to Docker image.

EDIT: updated `Dockerfile `content as per [comment](https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/issues/12#issuecomment-1140592321).

**Comment by n0rt0nthec4t** [comment]
Nice work. With the current version of the code it doesn't need to be copied to the accessory folder. Can be run from the "root" folder inside the docker container  by "node Nest_accfactory.js". This will create a new. "persist" folder in the same folder level, but probably not a bad idea as if update hap-nodejs won't override the one thats stored in its structure and therefore maintaining paired devices

I'll have some thinking how we can incorporate your work on this into the the repository

**Comment by krehman** [comment]
Nice! That really simplifies the `Dockerfile`. I have updated the [post](https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/issues/12#issuecomment-1140468044).

**TODO:**
- Use `Volume` in Docker to save the `persist` folder and `Nest_config.json` file every time Docker image is updated to avoid re-adding the accessories
- Provide flexibility to pass `Nest_config.json `as parameters to Docker image or similar functionality to avoid editing the image with `Nest_config.json `

**Comment by n0rt0nthec4t** [comment]
Would it help if nest_accfactory can take an argument to specify the config file location? example:

node Nest_accfactory.js /pathtoconfig/Nest_config.json

Update: Just committed code that allows this

**Comment by n0rt0nthec4t** [comment]
Here's what I've come up with testing on my raspberry pi installs:

**Dockerfile**
`FROM node:16

WORKDIR /opt/nest_accfactory

COPY package*.json ./
COPY Nest_accfactory.js ./
COPY Nest_camera_*.jpg ./
COPY HomeKitHistory.js ./
COPY nexusstreamer.js ./

RUN npm install

CMD ["node", "Nest_accfactory.js", "/opt/nest_accfactory/conf/Nest_config.json"]`


**.dockerignore**
`.dockerignore
Dockerfile
*.sample`

**build**
`docker build --tag nest_accfactory .`

**run**
`docker run --name nest_accfactory\
    --restart unless-stopped\
    --volume /home/pi/nest_accfactory/conf:/opt/nest_accfactory/conf\
    --volume /home/pi/nest_accfactory/persist:/opt/nest_accfactory/persist\
    --network host\
    --detach nest_accfactory`

obviously need to adjust the directory locations mapped in.. Something to test?

**Comment by krehman** [comment]
Nice! This works. `Persist` folder and `Nest_config.json` should now remain intact for docker image updates.  Thanks.

Note - we can use `FROM node:16-alpine3.14` but it doesn't allow you to go into the image using `docker exec`

**Dockerfile**
```
FROM node:16

WORKDIR /nest_accfactory

COPY package*.json ./

RUN npm install

COPY . .

CMD ["node", "Nest_accfactory.js", "/nest_accfactory/conf/Nest_config.json"]
```
**.dockerignore**
```
.dockerignore
Dockerfile
*.sample
```

**build-command**
```docker build --tag nest_accfactory .```

**run-command**
```
docker run --name nest_accfactory --restart unless-stopped \
   --volume /storage/nest_accfactory/conf:/nest_accfactory/conf \
   --volume /storage/nest_accfactory/persist:/nest_accfactory/persist \
   --network host --detach nest_accfactory
```

**Comment by n0rt0nthec4t** [comment]
> Note - we can use `FROM node:16-alpine3.14` but it doesn't allow you to go into the image using `docker exec`

I didn't think that was compatible with a RPI, hence why went straight to the node version for docker. I've been playing around this morning some more, and done some more refinements

**Dockerfile**
```
# base upon nodejs v17
FROM node:17

# working directory inside the container
WORKDIR /opt/Nest_accfactory

# copy require files into container image folder
COPY package.json ./
COPY Nest_accfactory.js ./
COPY Nest_camera_*.jpg ./
COPY HomeKitHistory.js ./
COPY nexusstreamer.js ./

# perform installation based on details in package.json
RUN npm install

# run the accessory
CMD ["node", "/opt/Nest_accfactory/Nest_accfactory.js", "/opt/Nest_accfactory/conf/Nest_config.json"]

# labels for the container
LABEL org.opencontainers.image.title="Nest_accfactory"
LABEL org.opencontainers.image.description="HomeKit integration for Nest devices based on HAP-NodeJS library"
LABEL org.opencontainers.image.version="v0.0.1"
```

**.dockerignore**
```
.dockerignore
Dockerfile
Nest_config.json
*.sample
*.MD
```

**run command** 
```
docker run --name nest_accfactory\
    --restart always\
    --volume /home/pi/Nest_accfactory/conf:/opt/Nest_accfactory/conf:ro\
    --volume /home/pi/Nest_accfactory/persist:/opt/Nest_accfactory/persist:rw\
    --network host\
    --detach nest_accfactory
```


Made the conf folder read-only and the persist folder read/write

**Comment by n0rt0nthec4t** [comment]
I have noticed a few times that the container stops running with exit code 143 OR live streaming fails after a period of time. Only SEEMS to be on my RPi 4 instance, not the RPI 3 one.. so looking into

Also testing the alpine node version

**Comment by n0rt0nthec4t** [comment]
testing with the folllowing dockerfile. Smaller image size by around 500MB.

Next task I'm thinking is to correctly set the timezone inside the container to mirror the host. Allows correct timestamps in logs

**Dockerfile**
```
# base upon nodejs v17
FROM node:17-alpine

# working directory inside the container
WORKDIR /opt/Nest_accfactory

# copy require files into container image folder
COPY package.json ./
COPY Nest_accfactory.js ./
COPY Nest_camera_*.jpg ./
COPY HomeKitHistory.js ./
COPY nexusstreamer.js ./

# perform installation based on details in package.json
RUN npm install

# run the accessory
CMD ["node", "/opt/Nest_accfactory/Nest_accfactory.js", "/opt/Nest_accfactory/conf/Nest_config.json"]

# labels for the container
LABEL org.opencontainers.image.title="Nest_accfactory"
LABEL org.opencontainers.image.description="HomeKit integration for Nest devices based on HAP-NodeJS library"
LABEL org.opencontainers.image.version="v0.0.1"
```

**Comment by krehman** [comment]
When I'm launching it, it sets the correct timezone for me.

```
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...
usermod: no changes
-------------------------------------
GID/UID
-------------------------------------
User uid:    911
User gid:    911
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-set-timezone: executing...
Set system timezone to America/Toronto.
```
Out of curiousity, any reason why not use `COPY . .` instead of specifying all the files?

```
COPY package.json ./
COPY Nest_accfactory.js ./
COPY Nest_camera_*.jpg ./
COPY HomeKitHistory.js ./
COPY nexusstreamer.js ./
```

**Comment by n0rt0nthec4t** [comment]
Guess copied the individual files by name as had other stuff in the directory when creating the container so didn't want that getting it

**Comment by n0rt0nthec4t** [comment]
**Dockerfile**
```
# base upon nodejs v17, apline version for smaller container size
FROM node:17-alpine

# Enable correct timezone inside container
# Pass TZ env from docker run
RUN apk update && apk add --no-cache tzdata

# working directory inside the container
WORKDIR /opt/Nest_accfactory

# copy require files into container image folder
COPY package.json ./
COPY Nest_accfactory.js ./
COPY Nest_camera_*.jpg ./
COPY HomeKitHistory.js ./
COPY nexusstreamer.js ./

# perform installation based on details in package.json
RUN npm install

# run the accessory
CMD ["node", "/opt/Nest_accfactory/Nest_accfactory.js", "/opt/Nest_accfactory/conf/Nest_config.json"]

# labels for the container
LABEL org.opencontainers.image.title="Nest_accfactory"
LABEL org.opencontainers.image.description="HomeKit integration for Nest devices based on HAP-NodeJS library"
LABEL org.opencontainers.image.version="v0.0.1"
```

Can pass in timezone location as per below. Adjust as required.

**run**
```
docker run --env TZ="Australia/Canberra"\
    --name nest_accfactory\
    --restart always\
    --volume /home/pi/Nest_accfactory/conf:/opt/Nest_accfactory/conf:ro\
    --volume /home/pi/Nest_accfactory/persist:/opt/Nest_accfactory/persist:rw\
    --network host\
    --detach nest_accfactory
```

Think we're almost ready to commit this to the repository??

Might also adjust the package file to bring in a beta version of hap-nodejs as it corrects some issue with HSKV recordings and eventlistter leaks

**Comment by krehman** [comment]
Just tested this. Looks good. I think we can commit it to the repo.

Thank you!

**Comment by n0rt0nthec4t** [comment]
https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories/commit/defe44e1fc9917b3b7083f29377c4ad9c3a4bcf6

:-) thanks very much for your help on doing this
