### ISSUE TITLE
sony tv

### ISSUE THREAD

**Issue by kontur11** [n0rt0nthec4t/HAP-NodeJS-Accessories#2]
How can I switch to Digital tuner dvbs?

**Comment by n0rt0nthec4t** [comment]
I *think*, you'd need to change this line (283)

this.__TVInputs[index].__uri = "tv:dvbt";

to

this.__TVInputs[index].__uri = "tv:dvbs";

**Comment by n0rt0nthec4t** [comment]
Uploaded a code change that seems to detect this in code..
