### ISSUE TITLE
Sony

### ISSUE THREAD

**Issue by kontur11** [n0rt0nthec4t/HAP-NodeJS-Accessories#3]
The tuner is detected, but you cannot switch to DVBS

**Comment by n0rt0nthec4t** [comment]
Does this command switch to the tuner and what is the result?

curl -H "Content-Type: application/json"   -X POST -H "X-Auth-PSK: xxxx"   -d '{"id": 13, "method": "setPlayContent", "version": "1.0", "params": [{"uri": "tv:dvbs"}]}' http://x.x.x.x/sony/avContent

update xxxx for PSK and x.x.x.x for TV IP

**Comment by n0rt0nthec4t** [comment]
Also, what does This return

curl -H "Content-Type: application/json"   -X POST -H "X-Auth-PSK: xxxx"   -d '{"id": 5, "method": "getSupportedApiInfo", "version": "1.0", "params": [{"services": ["system", "avContent"]}]}' http://x.x.x.x/sony/guide

**Comment by kontur11** [comment]
1.   {"error":[3,"invalid uri"],"id":13}
2.   {"error":[12,"getSupportedApiInfo"],"id":5}

**Comment by n0rt0nthec4t** [comment]
what does this return

curl -H "Content-Type: application/json"   -X POST -H "X-Auth-PSK: xxxx"   -d '{"id": 1, "method": "getSourceList", "version": "1.0", "params": [{"scheme": "tv"}]}' http://x.x.x.x/sony/avContent

**Comment by kontur11** [comment]
{"id":1,"result":[[{"source":"tv:dvbc"},{"source":"tv:dvbs"},{"source":"tv:dvbt"

**Comment by n0rt0nthec4t** [comment]
curl -H "Content-Type: application/json" -X POST -H "X-Auth-PSK: xxxx" -d '{"id": 13, "method": "setPlayContent", "version": "1.0", "params": [{"uri": "tv:dvbt"}]}' http://x.x.x.x/sony/avContent

curl -H "Content-Type: application/json" -X POST -H "X-Auth-PSK: xxxx" -d '{"id": 13, "method": "setPlayContent", "version": "1.0", "params": [{"uri": "tv:dvbc"}]}' http://x.x.x.x/sony/avContent

do these work? TV has to be on also

The update code I had should show 3 digital tuners in the app?

**Comment by kontur11** [comment]
{"error":[3,"invalid uri"],"id":13}

**Comment by n0rt0nthec4t** [comment]
curl -H "Content-Type: application/json" -X POST -H "X-Auth-PSK: xxxx" -d '{"id": 101, "method": "setPlayContent", "version": "1.0", "params": [{"uri": "tv:dvbc"}]}' http://x.x.x.x/sony/avContent

Changed API ID from 13 to 101

**Comment by kontur11** [comment]
{"error":[7,"Illegal State"],"id":101}

**Comment by n0rt0nthec4t** [comment]
weird.. if teh TV is on and the tuner is on dabs/c/t etc, what does this return 

curl -H "Content-Type: application/json"   -X POST -H "X-Auth-PSK: xxxx"   -d '{"id": 103, "method": "getPlayingContentInfo", "version": "1.0", "params": [""]}' http://x.x.x.x/sony/avContent

**Comment by kontur11** [comment]
{"id":103,"result":[{"dispNum":"145","durationSec":6900,"programMediaType":"tv","programTitle":"ЛЕГИОНЕР (16+)","source":"tv:dvbs","startDateTime":"2019-03-18T23:45:00+0300","title":"МУЖСКОЕ КИНО","tripletStr":"112.1.114","uri":"tv:dvbs?trip=112.1.114&srvName=%D0%9C%D0%A3%D0%96%D0%A1%D0%9A%D0%9E%D0%95%20%D0%9A%D0%98%D0%9D%D0%9E"}]}

**Comment by n0rt0nthec4t** [comment]
ok, I have no idea why the Sony API wont accept "tv:dvbs" etc for changing inputs. does it change to otherwise like HDMI etc?

**Comment by kontur11** [comment]
https://pro-bravia.sony.net/data/samples/displaycontrol.zip
No command digital tuner, only HDMI, composite and scart

**Comment by n0rt0nthec4t** [comment]
As I said, I have no idea why that API isn't working on your TV to set inputs. You might need to play around with the curl commands to see what allows selecting the tv:* inputs. The documented API is "setPlayContent". and from what I've searched, all plugins developed for Sony TVs use this to set inputs.

**Comment by kontur11** [comment]
Looks like the deadline should look like this?   tv: dvbs? trip = ХХХХХ & srvName = ХХХХХ  
As after command "getPlayingContentInfo"

**Comment by n0rt0nthec4t** [comment]
What happens if you use something like the TV:dvbs?trip= .... into the setPlayContent command form above? like

curl -H "Content-Type: application/json" -X POST -H "X-Auth-PSK: xxxx" -d '{"id": 13, "method": "setPlayContent", "version": "1.0", "params": [{"uri": "tv:dvbs?trip=....."}]}' http://x.x.x.x/sony/avContent

**Comment by kontur11** [comment]
"tv:dvbs?trip=112.1.114&srvName=%D0%9C%D0%A3%D0%96%D0%A1%D0%9A%D0%9E%D0%95%20%D0%9A%D0%98%D0%9D%D0%9E"
answer {"id":13,"result":[]}

**Comment by n0rt0nthec4t** [comment]
so did it switch the inputs?

**Comment by kontur11** [comment]
Yes, switches to the same channel

**Comment by n0rt0nthec4t** [comment]
try the code I just uploaded. Includes a routine if you change line 72 from

        this.__buildInputList(false);

to 

        this.__buildInputList(true);

This will added the channels in as inputs. May have to removed/re-add accessories

See if that switches as you wish.

**Comment by kontur11** [comment]
There was no way to check. Today launched, everything works fine! Check with 222 line there is a small error, easily fixed. 5 stars!!!

**Comment by kontur11** [comment]
Lay out the accessory separately, for easy searching. Perhaps a lot of it will come in handy!
