### ISSUE TITLE
fakeeve-history

### ISSUE THREAD

**Issue by kontur11** [n0rt0nthec4t/HAP-NodeJS-Accessories#4]
Sorry, I couldn't ask a question in fakeeve-history. I can 't figure out how to run your recoded fakeeve-history so that the temperature accessories in hap-nodejs work with the history?

**Comment by n0rt0nthec4t** [comment]
I haven’t finished recoding it yet, as got dirverted with some other work.. plan is to get it going soon

**Comment by kontur11** [comment]
Thank you , I will wait!

**Comment by n0rt0nthec4t** [comment]
I've decided not to work on that directly, but created/creating my own method for logging history form developed accessories.. Its modular enough could overlay to expose things to a "fake eve" type thing

**Comment by kontur11** [comment]
Good afternoon! I will be very grateful if you share your method. Will you post it on github?

**Comment by n0rt0nthec4t** [comment]
It will be posted here with my accessory source codes. Just testing in my home environment atm

**Comment by n0rt0nthec4t** [comment]
Ok, I have something sort of going with my accessories and getting into Eve app (Atleast for a garagedoor and temperature sensor. Still testing on stuff
![IMG_0874](https://user-images.githubusercontent.com/19759130/81266594-5a1ca480-9088-11ea-9da9-fa269b026bc8.jpeg)

**Comment by n0rt0nthec4t** [comment]
Uploaded an initial commit with example using garage door for history and linking into EveHome
