### ISSUE TITLE
Question about volume

### ISSUE THREAD

**Issue by Sinled** [n0rt0nthec4t/HAP-NodeJS-Accessories#6]
Hi,
i am trying to adapt you code to my yamaha reciever and i am struggling to setup 
volume controls in homekit, is there distinct control for this service or it volume is changed is some implicit way?

**Comment by n0rt0nthec4t** [comment]
The volume controls in HomeKit are trigger by the remote control app on your iPhone/iPad. Using then volume up/down buttons on say your iPhone will trigger the .SetVolume callback and passing's either Characteristic.VolumeSelector.INCREMENT or Characteristic.VolumeSelector.DECREMENT as the value. You then take action from those to make your AMP volume change

**Comment by Sinled** [comment]
Thanks for reply!

**Comment by n0rt0nthec4t** [comment]
No worries. hope it helped you out
