### ISSUE TITLE
Nest Camera HKSV using HAP-NodeJS

### ISSUE THREAD

**Issue by krehman** [n0rt0nthec4t/HAP-NodeJS-Accessories#8]
Hello, 

I'm trying out the Nest Camera HKSV that has been developed. I'm starting from scratch and running into the following issue. 

1. Under '`node_modules`', execute `git clone https://github.com/n0rt0nthec4t/HAP-NodeJS`
2. Run `npm install` and resolve any issues with dependencies
3. Run `DEBUG=* ts-node --files src/Core.ts` to ensure the server runs.
4. Renamed the existing accessories folder, `mv src/accessories/ src/accessories-bak`
5. Created a new folder named `accessories `and copied over the following files from `https://github.com/n0rt0nthec4t/HAP-NodeJS-Accessories`
> Nest_cameraoff.jpg
nexusstreamer.js
usonic_measure.py
IrrigationSystem_config.json
Nest_config.json
README.md
Nest_accfactory.js
Nest_offline.h264
HomeKitHistory.js
Nest_cameraoff.h264
Nest_offline.jpg
usonic_measure.c
6. Under `Nest_config.json` copied over the session token from `http://home.nest.com/session`. Note - I have migrated my account Google and not using native Nest credentials, but when accessing /session, it displays a token
7. Run `DEBUG=* ts-node --files src/Core.ts`  and faced with the following error.

```
/home/ha/node_modules/HAP-NodeJS/src/accessories/Nest_accfactory.js:881
    this.controller = deviceData.device_type == "doorbell" ? new DoorbellController(options) : new CameraController(options);
                                                             ^
TypeError: DoorbellController is not a constructor
    at CameraClass.addDoorbellCamera (/home/ha/node_modules/HAP-NodeJS/src/accessories/Nest_accfactory.js:881:62)
    at processDeviceforHomeKit (/home/ha/node_modules/HAP-NodeJS/src/accessories/Nest_accfactory.js:2555:44)
    at /home/ha/node_modules/HAP-NodeJS/src/accessories/Nest_accfactory.js:2621:17
    at Array.forEach (<anonymous>)
    at /home/ha/node_modules/HAP-NodeJS/src/accessories/Nest_accfactory.js:2620:66
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Any idea what I'm doing wrong?

Thank you!

**Comment by n0rt0nthec4t** [comment]
Thanks for reaching out and having a go with this. Couple of things first :-)

1) I've only tested with non-migrated Nest account, so not sure if a "Google" account for the Nest devices would make much difference. 
2) Never tested it with typescript engine

So, my suggestion, do a clean install of hap-nodejs. (npm install hap-nodejs) probably on a system you don't have homebridge installed on
 
From there, removed any "accessory" files and "gstreamer" files from the accessories folder

Afterwards, the accessories folder should have the following files in there 

HomeKitHistory.js   
Nest_cameraoff.h264  
Nest_config.json   
Nest_offline.jpg  
types.d.ts      
types.js
Nest_accfactory.js  
Nest_cameraoff.jpg   
Nest_offline.h264  
nexusstreamer.js  
types.d.ts.map  
types.js.map

install other required modules such as ws, axios, pbf

from the root folder where hap-nodejs was installed to run: node Core.js

**Comment by krehman** [comment]
Thanks. I'm getting the following error after getting it setup. This occurs when clicking on the video to stream.

```
[Nest Cam Outdoor A3C7] Snapshot request handler provided empty image buffer!
Error: This callback function has already been called by someone else; it can only be called one time.
    at /home/ha/node_modules/hap-nodejs/src/lib/util/once.ts:7:13
    at streamCallback (/home/ha/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:730:7)
    at /home/ha/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:917:57
    at CameraClass.<anonymous> (/home/ha/node_modules/hap-nodejs/dist/accessories/Nest_accfactory.js:1515:9)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

**Comment by n0rt0nthec4t** [comment]
Do you have an Ffmpeg binary installed and in the path? I've used these binaries on my Rpi3 and Rpi4

https://github.com/homebridge/ffmpeg-for-homebridge

I think also, need to change a line in the nexusstreamer file, to account for a google account. Comment out line 508 and 523 and uncomment lines 509 and 524. All untested as I said with google accounts

**Comment by n0rt0nthec4t** [comment]
@krehman did you managed to get working? curious how you went

**Comment by krehman** [comment]
@n0rt0nthec4t I was able to successfully install the plugin as you suggested above with installing FFMPEG and commenting the lines out for Google accounts, but was unable to get a stream going. I might need to use the Google auth for authentication.

  ```
HAP-NodeJS:Characteristic [Selected RTP Stream Configuration] Received error from set handler Error: ffmpeg process creation failed!
    at CameraClass.<anonymous> (/home/ha/node_modules/hap-nodejs/dist/accessories/Nest_accfactory.js:1476:18)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) +15s
Error: This callback function has already been called by someone else; it can only be called one time.
    at /home/ha/node_modules/hap-nodejs/src/lib/util/once.ts:7:13
    at streamCallback (/home/ha/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:730:7)
    at /home/ha/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:917:57
    at CameraClass.<anonymous> (/home/ha/node_modules/hap-nodejs/dist/accessories/Nest_accfactory.js:1515:9)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

**Comment by n0rt0nthec4t** [comment]
No worries.. I might see over the next week if I can setup a spare camera I have into a "google" account and see what's what.

**Comment by krehman** [comment]
Thanks. Maybe it's not the authentication and something else with this function `CameraClass.prototype.__buildVideoStream = function(request, sessionInfo, callback) `. Maybe I don't have the right `ffmpeg `installed.

**Comment by n0rt0nthec4t** [comment]
I just setup via the Nest app a new google account and added my Nest Outdoor cam.. My code fails with lots of HTTP errors with debugging turned on in the Nest_config.json file. Hrmm.. have to work things out

**Comment by krehman** [comment]
Sounds good - makes sense. Thanks! I'll try tinkering around as well when I get a chance.

**Comment by n0rt0nthec4t** [comment]
Ok, have something working, but need to refine it more. Thanks for forcing me to actually test with a google account

**Comment by n0rt0nthec4t** [comment]
I’ve uploaded a couple of new files that should allow a google account to work. In the config there is a new item “RefreshToken” which is required. This can be obtained via the same method that homebridge-nest-cam uses. Clear out the “SessionToken” line.  

See how that goes

**Comment by krehman** [comment]
Thanks. I was able to get a thumbnail image, but as soon as I click on it to view the stream, it errors out.

```
  HAP-NodeJS:Characteristic [Selected RTP Stream Configuration] Received error from set handler Error: ffmpeg process creation failed!
    at CameraClass.<anonymous> (/home/ha/node_modules/hap-nodejs/dist/accessories/Nest_accfactory.js:1477:18)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) +2m
Error: This callback function has already been called by someone else; it can only be called one time.
    at /home/ha/node_modules/hap-nodejs/src/lib/util/once.ts:7:13
    at streamCallback (/home/ha/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:730:7)
    at /home/ha/node_modules/hap-nodejs/src/lib/camera/RTPStreamManagement.ts:917:57
    at CameraClass.<anonymous> (/home/ha/node_modules/hap-nodejs/dist/accessories/Nest_accfactory.js:1516:9)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

**Comment by n0rt0nthec4t** [comment]
Seems to be pointing to an ffmpeg issue

**Comment by krehman** [comment]
> Seems to be pointing to an ffmpeg issue

Any special ffmpeg you have installed? Maybe something isn’t configured correctly in my environment. 

Thanks.

**Comment by n0rt0nthec4t** [comment]
What’s your environment running on? Software and hardware?

what happens if you try to run ffmpeg from the hap-nodejs folder ?

My output below:
pi@raspberrypi:~/HAP-NodeJS/dist $ ffmpeg
ffmpeg version 5.0 Copyright (c) 2000-2022 the FFmpeg developers
  built with gcc 6.3.0 (Raspbian 6.3.0-18+rpi1+deb9u1) 20170516
  configuration: --pkgconfigdir=/build/workspace/lib/pkgconfig --prefix=/build/workspace --pkg-config-flags=--static --extra-cflags=-I/build/workspace/include --extra-ldflags=-L/build/workspace/lib --extra-libs='-lpthread -lm' --enable-static --disable-debug --disable-shared --disable-ffplay --disable-doc --enable-openssl --enable-gpl --enable-version3 --enable-nonfree --enable-pthreads --enable-libvpx --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libx264 --enable-runtime-cpudetect --enable-libfdk-aac --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-decoder=h264 --enable-network --enable-protocol=tcp --enable-libspeex --enable-demuxer=rtsp --enable-omx-rpi --enable-mmal --enable-indev=alsa --enable-outdev=alsa
  libavutil      57. 17.100 / 57. 17.100
  libavcodec     59. 18.100 / 59. 18.100
  libavformat    59. 16.100 / 59. 16.100
  libavdevice    59.  4.100 / 59.  4.100
  libavfilter     8. 24.100 /  8. 24.100
  libswscale      6.  4.100 /  6.  4.100
  libswresample   4.  3.100 /  4.  3.100
  libpostproc    56.  3.100 / 56.  3.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
pi@raspberrypi:~/HAP-NodeJS/dist $

**Comment by krehman** [comment]
It works! It's a VM with Ubuntu 22.04 LTS on a Win 10 machine.

I had to install `sudo apt install ffmpeg` and then it worked. This is great but no sound. 

```
ha@hap-nodejs:~/node_modules/hap-nodejs$ ffmpeg
ffmpeg version 4.4.1-3ubuntu5 Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 11 (Ubuntu 11.2.0-18ubuntu1)
  configuration: --prefix=/usr --extra-version=3ubuntu5 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```

**Comment by n0rt0nthec4t** [comment]
OK, progress.. I cant see from that version of FFMPEG is libspeex and libfdk-aac are enabled for that build. They require for audio (noting that mine doesn't record audio yet, but can use audio and two/way chat)

install a binary version from here.
https://github.com/homebridge/ffmpeg-for-homebridge

might be this one
https://github.com/homebridge/ffmpeg-for-homebridge/releases/download/v0.1.0/ffmpeg-debian-x86_64.tar.gz

**Comment by krehman** [comment]
Alright, that worked. Audio is working now and recording as well. 

Installed the following for Ubuntu.
`sudo curl -Lf# https://github.com/homebridge/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-debian-$(uname -m).tar.gz | sudo tar xzf - -C / --no-same-owner`

As stated above, audio is not working on recording, but everything else is working spot-on. 

Thank you! This is fantastic!

**Comment by n0rt0nthec4t** [comment]
Awesome.. Glad you got it all working now. I'l upload a new version once I work out audio recording. Let to installed it as my main accessory for our Nest Hello. Like you, also have a Nest Outdoor Cam, but I find that a little less reliable with motion detection over the Nest Hello

Will close this now. Reach out if find anything else not as expected or any issues. Be good for someone else other than myself to use :-)
